### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by DanielLenz** [mirapy-org/MiraPy#39]
Hi, I'm currently reviewing `mirapy` for publication in JOSS (https://github.com/openjournals/joss-reviews/issues/1557).

Could you add a suite of (unit)tests to the project that verify the software? It's one of the JOSS requirements.

Thank you!

**Comment by swapsha96** [comment]
Currently, I have written [tests](https://github.com/mirapy-org/mirapy/tree/master/mirapy/fitting/tests) for `fitting` module. Since other modules require large datasets for testing, I have not written any specific tests for them right now. You can run the tests by running the following command in the cloned repository:
```
python setup.py test
```

Since the requirement says:

>  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

I hope this requirement is satisfied.

**Comment by DanielLenz** [comment]
Thanks for pointing that out! I agree that it's difficult to test parts of the package that require large data, but part of the JOSS requirements is that most of the codebase is tested, not only a small part of it.

It would be awesome if you could add some very simple unit tests, and possibly provide the test coverage as well.

**Comment by swapsha96** [comment]
Currently, the test coverage is [43%](https://coveralls.io/github/mirapy-org/mirapy).

**Comment by DanielLenz** [comment]
Thanks for adding all these tests!
